export const PATIENT_COMMUNICATION_CHANNELS = {
  EMAIL: 'Email',
  SMS: 'Sms',
  WHATSAPP: 'WhatsApp',
};

export const PATIENT_COMMUNICATION_CHANNELS_VALUES = Object.values(
  PATIENT_COMMUNICATION_CHANNELS,
);

export const PATIENT_COMMUNICATION_TYPES = {
  REFERRAL_CREATED: 'Referral created',
  CERTIFICATE: 'Certificate',
};

export const PATIENT_COMMUNICATION_TYPES_VALUES = Object.values(
  PATIENT_COMMUNICATION_TYPES,
);
