export const LOCATION_AVAILABILITY_STATUS = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  OCCUPIED: 'OCCUPIED',
};

export const LOCATION_AVAILABILITY_STATUS_LABELS = {
  [LOCATION_AVAILABILITY_STATUS.AVAILABLE]: 'Available',
  [LOCATION_AVAILABILITY_STATUS.RESERVED]: 'Reserved',
  [LOCATION_AVAILABILITY_STATUS.OCCUPIED]: 'Occupied',
};

export const LOCATION_AVAILABILITY_TAG_CONFIG = {
  [LOCATION_AVAILABILITY_STATUS.AVAILABLE]: {
    label: LOCATION_AVAILABILITY_STATUS_LABELS[LOCATION_AVAILABILITY_STATUS.AVAILABLE],
    color: '#44AD72',
    background: '#EDF7F1',
  },
  [LOCATION_AVAILABILITY_STATUS.RESERVED]: {
    label: LOCATION_AVAILABILITY_STATUS_LABELS[LOCATION_AVAILABILITY_STATUS.RESERVED],
    color: '#888888',
    background: '#F4F4F4',
  },
  [LOCATION_AVAILABILITY_STATUS.OCCUPIED]: {
    label: LOCATION_AVAILABILITY_STATUS_LABELS[LOCATION_AVAILABILITY_STATUS.OCCUPIED],
    color: '#888888;',
    background: '#F4F4F4',
  },
};
