name: CD Setup
description: Set up Pulumi, Tailscale, and K8S
inputs:
  ops-ssh-key:
    description: SSH key for ops repo
    required: true
  ops-ref:
    description: Ref to checkout in ops repo
    required: true
    default: main
  tailscale-oauth:
    description: Tailscale OAuth key
    required: true
  k8s-core:
    description: K8S core name
runs:
  using: composite
  steps:
    - name: Checkout ops
      uses: actions/checkout@v4
      with:
        repository: beyondessential/ops
        ssh-key: ${{ inputs.ops-ssh-key }}
        path: ops
        ref: ${{ inputs.ops-ref }}
    - name: Remove ops/.git so pulumi doesn't get confused
      shell: bash
      run: rm -rf ops/.git

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm

    - name: Prepare pulumi
      shell: bash
      working-directory: ops/pulumi
      run: npm ci

    - name: Pre-install pulumi
      uses: pulumi/actions@v5

    - name: Connect to Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-secret: ${{ inputs.tailscale-oauth }}
        tags: tag:infra,tag:infra-gha-deploy

    - name: Configure kubeconfig
      if: inputs.k8s-core
      shell: bash
      run: tailscale configure kubeconfig k8s-operator-${{ inputs.k8s-core }}

    - name: Test kubernetes cluster for readiness
      if: inputs.k8s-core
      shell: bash
      run: kubectl get namespace/tamanu-system
