export const NON_SYNCING_TABLES = [
  'attachments',
  'local_system_facts',
  'one_time_logins',
  'refresh_tokens',
  'patient_communications',
  'patient_vrs_data',
  'SequelizeMeta',
  'signers',
  'sync_sessions',
  'user_localisation_caches',
  'fhir_materialise_jobs',
  'jobs',
  'job_workers',
  'user_recently_viewed_patients',
];
