---
- name: Lan Server
  hosts: ec2
  tasks:
  # Install nodejs
  - name: Ensure Nodejs is installed via Chocolatey
    win_chocolatey:
      name: nodejs
      version: 16.16.0
      state: present

  - name: Ensure PostgreSQL is installed via Chocolatey
    win_chocolatey:
      name: postgresql
      state: present
      version: 12.8.1
      install_args:
        - "/Password:{{ lookup('password', 'secrets/lan/postgres/' + inventory_hostname_short) }}"
