@token=fake-token
@server=https://central-demo.tamanu.io
@since=0

### Log in
POST {{server}}/api/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### Get current user details
GET {{server}}/api/whoami
Authorization: Bearer {{token}}

### List users
GET {{server}}/api/sync/user?since={{since}}
Authorization: Bearer {{token}}

### Create an account
# The server will hash the password if provided
POST {{server}}/api/sync/user
Content-Type: application/json
Authorization: Bearer {{token}}

[{
    "data": {
        "email": "my.email@domain.com",
        "password": "open-sesame",
        "displayName": "Test User",
        "role": "practitioner"
    }
}]

### Update user details (including changing a password)
POST {{server}}/api/sync/user
Content-Type: application/json
Authorization: Bearer {{token}}

[{
    "data": {
        "id": "my-user-id",
        "password": "open-sesame",
    }
}]
