@token=fake-token
@server=https://sync-dev.tamanu.io

### Delete a survey screen component
DELETE {{server}}/v1/sync/surveyScreenComponent/program-snap-fiji-2%2Fsurvey-snap-fiji-2%2Fcomponent-FijSNAP_18  HTTP/1.1
Authorization: Bearer {{token}}
