import { INVOICE_PAYMENT_STATUSES, INVOICE_STATUSES } from '@tamanu/constants';

export const INVOICE_STATUS_LABELS = {
  [INVOICE_STATUSES.CANCELLED]: 'Cancelled',
  [INVOICE_STATUSES.IN_PROGRESS]: 'In progress',
  [INVOICE_STATUSES.FINALISED]: 'Finalised',
};

export const INVOICE_STATUS_OPTIONS = [
  {
    value: INVOICE_STATUSES.CANCELLED,
    label: INVOICE_STATUS_LABELS[INVOICE_STATUSES.CANCELLED],
  },
  {
    value: INVOICE_STATUSES.IN_PROGRESS,
    label: INVOICE_STATUS_LABELS[INVOICE_STATUSES.IN_PROGRESS],
  },
  {
    value: INVOICE_STATUSES.FINALISED,
    label: INVOICE_STATUS_LABELS[INVOICE_STATUSES.FINALISED],
  },
];

export const INVOICE_STATUS_COLORS = {
  [INVOICE_STATUSES.CANCELLED]: '#FFCC24',
  [INVOICE_STATUSES.IN_PROGRESS]: '#F76853',
  [INVOICE_STATUSES.FINALISED]: '#47CA80',
};

export const INVOICE_PAYMENT_STATUS_LABELS = {
  [INVOICE_PAYMENT_STATUSES.UNPAID]: 'Unpaid',
  [INVOICE_PAYMENT_STATUSES.PAID]: 'Paid',
};

export const INVOICE_PAYMENT_STATUS_OPTIONS = [
  {
    value: INVOICE_PAYMENT_STATUSES.UNPAID,
    label: INVOICE_PAYMENT_STATUS_LABELS[INVOICE_PAYMENT_STATUSES.UNPAID],
  },
  {
    value: INVOICE_PAYMENT_STATUSES.PAID,
    label: INVOICE_PAYMENT_STATUS_LABELS[INVOICE_PAYMENT_STATUSES.PAID],
  },
];
